export type ApiSuccess<T> = {
  success: true;
  data: T;
};

export type ApiError = {
  success: false;
  message: string;
};

export type ApiResponse<T> = ApiSuccess<T> | ApiError;

export type PriorityLevel = "low" | "medium" | "high" | "critical";

export type DetectionPoint = {
  id: string;
  /** Human-readable location label (neighborhood / street). */
  location: string;
  lat: number;
  lng: number;
  /** Number of litter / pollution objects detected in the image. */
  litterCount: number;
  /** Normalized garbage density score in the 0-100 range. */
  densityScore: number;
  priority: PriorityLevel;
  /** Street View image reference used for the detection. */
  imageRef: string;
  capturedAt: string;
};

export type DetectedObject = {
  label: string;
  score: number;
};

/** An object/category with how many times it appears (Turkish label). */
export type LabeledCount = {
  label: string;
  count: number;
};

/** One scanned Street View direction with its proxied image URL. */
export type DirectionImage = {
  /** ön | arka | sağ | sol */
  label: string;
  heading: number;
  url: string;
};

/** Result returned by GET /api/analyze for a single location/address. */
export type AnalysisResult = {
  address: string;
  lat: number;
  lng: number;
  litterCount: number;
  densityScore: number;
  priority: PriorityLevel;
  /** Local proxy path for the front Street View image of this location. */
  streetViewUrl: string;
  /** The four scanned directions (front/right/back/left) with images. */
  directionImages: DirectionImage[];
  /** Litter / waste items found (Turkish labels). */
  litterItems: LabeledCount[];
  /** Context items (people, vehicles, furniture) — NOT pollution. */
  contextItems: LabeledCount[];
  /** Flattened object list (kept for record statistics). */
  objects: DetectedObject[];
  /** Number of directions scanned (front/right/back/left). */
  directionsScanned: number;
  /** Temiz | Orta | Kirli */
  cleanliness: string;
  /** Natural-language assessment (Gemini or heuristic fallback). */
  assessment: string;
  /** Short note on urban order / tidiness (şehir düzeni). */
  cityOrder: string;
  /** True when the assessment was generated by Gemini AI. */
  aiAssessment: boolean;
  /** Which engine produced the analysis. */
  analysisModel: "vision" | "object-detection";
};

/** A persisted analysis (data accumulation). */
export type AnalysisRecord = AnalysisResult & {
  id: string;
  createdAt: string;
};
